#
# Makefile for a POSIX compliant make utility
# Refer to http://www.opengroup.org/onlinepubs/009695399/utilities/make.html
#
# FieldTalk Modbus Master C++ Library samples build
#
# proconX Pty Ltd
#


default:
	cd tcpsimple && ./make
	cd tcpsimple.c && ./make
	cd sersimple && ./make
	cd modpoll && ./make
	cd adam && ./make

