.TH "design" 3 "29 Jan 2010" "Version Library version 2.6" "FieldTalk Modbus Master C++ Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
design \- Design Background 
FieldTalk is based on a programming language neutral but object oriented design model.
.PP
This design approach enables us to offer the protocol stack for the languages C++, C#, Visual Basic .NET, Java and Object Pascal while maintaining similar functionality.
.PP
The C++ editions of the protocol stack have also been designed to support multiple operating system and compiler platforms, including real-time operating systems. In order to support this multi-platform approach, the C++ editions are built around a lightweight OS abstraction layer called \fIHMLIB\fP.
.PP
During the course of implementation, the usability in automation, control and other industrial environments was always kept in mind. 
