.TH "notices" 3 "29 Jan 2010" "Version Library version 2.6" "FieldTalk Modbus Master C++ Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
notices \- Notices 
\fBDisclaimer\fP:
.PP
proconX Pty Ltd makes no warranty for the use of its products, other than those expressly contained in the Company's standard warranty which is detailed in the Terms and Conditions located on the Company's Website. The Company assumes no responsibility for any errors which may appear in this document, reserves the right to change devices or specifications detailed herein at any time without notice, and does not make any commitment to update the information contained herein. No licenses to patents or other intellectual property of proconX are granted by the Company in connection with the sale of proconX products, expressly or by implication. proconX products are not authorized for use as critical components in life support devices or systems.
.PP
This FieldTalk\*{(TM)\*}  library was developed by:
.br
 proconX Pty Ltd, Australia.
.br
 Copyright (C) 2002-${now.year}. All rights reserved.
.PP
proconX and FieldTalk are trademarks of proconX Pty Ltd. Modbus is a registered trademark of Schneider Automation Inc. All other product and brand names mentioned in this document may be trademarks or registered trademarks of their respective owners. 
